apiVersion: v1
kind: Pod
metadata:
  labels:
    app: base-java11
  name: base-java11
spec:
  containers:
  - env:
    image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_base_java11:latest
    imagePullPolicy: Always
    command: ["/bin/sleep", "180d"]
    name: base-java11
  hostname: base-java11
  imagePullSecrets:
  - name: aws-arkcase-pull
